GET {{host}}:{{port}}/users

> {%
    client.test(
        "Response status is 200",
        function () {
            client.assert(response.status === 200, "Response status is not 200");
        }
    );


%}


